[package]
name = "aoc_2020_1_1"
version = "0.1.0"
authors = ["Reese Robertson <rrobertson@purestorage.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
